# ============================================================ rm
rm -r dataiss 
# ============================================================ mkdir
mkdir -p ./dataiss/trigeff/pdf
mkdir -p ./dataiss/tofeff/pdf
mkdir -p ./dataiss/trdeff/pdf
mkdir -p ./dataiss/ecaleff/pdf
mkdir -p ./dataiss/trkeff/pdf
# ============================================================ mv
mv ./*trigeff.pdf ./dataiss/trigeff/pdf/
mv ./*trigeff.root ./dataiss/trigeff/
mv ./*tofeff.pdf ./dataiss/tofeff/pdf/
mv ./*tofeff.root ./dataiss/tofeff/
mv ./*trdeff.pdf ./dataiss/trdeff/pdf/
mv ./*trdeff.root ./dataiss/trdeff/
mv ./*ecaleff.pdf ./dataiss/ecaleff/pdf/
mv ./*ecaleff.root ./dataiss/ecaleff/
mv ./*trkeff.pdf ./dataiss/trkeff/pdf/
mv ./*trkeff.root ./dataiss/trkeff/