# ============================================================ rm
rm -r dataiss 
# ============================================================ mkdir
mkdir -p ./dataiss/nele/pdf
mkdir -p ./dataiss/npos/pdf
# ============================================================ mv
mv ./*nele.pdf ./dataiss/nele/pdf/
mv ./*nele.root ./dataiss/nele/
mv ./*npos.pdf ./dataiss/npos/pdf/
mv ./*npos.root ./dataiss/npos/