# ============================================================ rm
rm -r dataiss 
# ============================================================ mkdir
mkdir -p ./dataiss/trigeff
mkdir -p ./dataiss/tofeff
mkdir -p ./dataiss/trdeff
mkdir -p ./dataiss/ecaleff
mkdir -p ./dataiss/trkeff
# ============================================================ mv
mv ./*trigeff.pdf ./dataiss/trigeff/
mv ./*trigeff.root ./dataiss/trigeff/
mv ./*tofeff.pdf ./dataiss/tofeff/
mv ./*tofeff.root ./dataiss/tofeff/
mv ./*trdeff.pdf ./dataiss/trdeff/
mv ./*trdeff.root ./dataiss/trdeff/
mv ./*ecaleff.pdf ./dataiss/ecaleff/
mv ./*ecaleff.root ./dataiss/ecaleff/
mv ./*trkeff.pdf ./dataiss/trkeff/
mv ./*trkeff.root ./dataiss/trkeff/