# ============================================================ rm
rm -r dataiss 
# ============================================================ mkdir
mkdir -p ./dataiss/nele/root
mkdir -p ./dataiss/npos/root
# ============================================================ mv
mv ./*nele.pdf ./dataiss/nele/
mv ./*nele.root ./dataiss/nele/root/
mv ./*npos.pdf ./dataiss/npos/
mv ./*npos.root ./dataiss/npos/root/